controller_manager:
  ros__parameters:
    update_rate: 100  # Hz

    joint_state_broadcaster:
      type: joint_state_broadcaster/JointStateBroadcaster

    arm_controller:
      type: joint_trajectory_controller/JointTrajectoryController

    gripper_controller:
      type: joint_trajectory_controller/JointTrajectoryController


arm_controller:
  ros__parameters:
    joints:
      - base_link_link1
      - link1_link2
      - link2_link3
      - link3_link4
      - link4_link5
      - link5_tcp_connector
    command_interfaces:
      - position
    state_interfaces:
      - position
      - velocity
    gains:
      base_link_link1: {p: 200.0, d: 1.0}
      link1_link2: {p: 200.0, d: 1.0}
      link2_link3: {p: 200.0, d: 1.0}
      link3_link4: {p: 200.0, d: 1.0}
      link4_link5: {p: 200.0, d: 1.0}
      link5_tcp_connector: {p: 200.0, d: 1.0}
    trajectory_execution.execution_duration_monitoring: false
    allow_partial_joints_goal: true


gripper_controller:
  ros__parameters:
    joints:
      - tcp_connector_gripper_right
      - tcp_connector_gripper_left
    command_interfaces:
      - position
    state_interfaces:
      - position
      - velocity
    gains:
      tcp_connector_gripper_right: {p: 50.0, d: 0.5}
      tcp_connector_gripper_left: {p: 50.0, d: 0.5}
